apiVersion: v1
kind: Service
metadata:
  name: gapps
  namespace: customer-U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso
  labels:
    app.kubernetes.io/name: gapps
    app.kubernetes.io/instance: U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso-gapps
    app.kubernetes.io/version: f1b6939
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso-f8987309-3069-4580-91c8-89b885249c57
    app.kubernetes.io/managed-by: syncable
    syncable.dev/customer-id: U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso
    syncable.dev/project-id: f8987309-3069-4580-91c8-89b885249c57
    environment: production
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gapps
    app.kubernetes.io/instance: U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso-gapps
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
