apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gapps-hpa
  namespace: customer-8cb48a92f47d8b2d8301f1dd2ebde31b85aa85d714b07e7c16
  labels:
    app.kubernetes.io/name: gapps
    app.kubernetes.io/instance: 8cb48a92-gapps
    app.kubernetes.io/version: 3c48685
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: 8cb48a92f47d8b2d8301f1dd2ebde31b85aa85d714b07e7c16
    app.kubernetes.io/managed-by: syncable
    syncable.dev/customer-id: U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso
    syncable.dev/project-id: 234140b4-de88-42b2-8774-76cb0bacfffc
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gapps
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
