apiVersion: apps/v1
kind: Deployment
metadata:
  name: gapps
  namespace: customer-8cb48a92f47d8b2d8301f1dd2ebde31b85aa85d714b07e7c16
  labels: &a1
    app.kubernetes.io/name: gapps
    app.kubernetes.io/instance: 8cb48a92-gapps
    app.kubernetes.io/version: fe2ec23
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: 8cb48a92f47d8b2d8301f1dd2ebde31b85aa85d714b07e7c16
    app.kubernetes.io/managed-by: syncable
    syncable.dev/customer-id: U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso
    syncable.dev/project-id: 234140b4-de88-42b2-8774-76cb0bacfffc
    environment: production
  annotations: &a2
    backstage.io/kubernetes-id: gapps
    syncable.dev/image-digest: sha256:f1d06a5b561842de3cdb6062836124526de50774a8dba859ae25884b90c5d774
    syncable.dev/generated-by: backstage-scaffolder
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: gapps
      app.kubernetes.io/instance: 8cb48a92-gapps
  template:
    metadata:
      labels: *a1
      annotations: *a2
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        fsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: gapps
          image: europe-docker.pkg.dev/syncable-461014/syncable-customer-images/customers/u8tnfi7z1nhnf6zhq2tzttlidsxukjso-df7f4cf7/234140b4-de88-42b2-8774-76cb0bacfffc-c89a9795-gapps:fe2ec23
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: gapps-config
                  key: PORT
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      terminationGracePeriodSeconds: 30
