apiVersion: apps/v1
kind: Deployment
metadata:
  name: gapps
  namespace: customer-9095eef245584e5513bbe7a21529cd0b88065a6f321e36e304
  labels: &a1
    app.kubernetes.io/name: gapps
    app.kubernetes.io/instance: 9095eef2-gapps
    app.kubernetes.io/version: 2e3842f
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: 9095eef245584e5513bbe7a21529cd0b88065a6f321e36e304
    app.kubernetes.io/managed-by: syncable
    syncable.dev/customer-id: XvtIvof7pmCZSfw9g1y1NInJNYooOIBa
    syncable.dev/project-id: de0916fc-44ee-44f2-a104-5788f3f0ab0a
    environment: production
  annotations: &a2
    backstage.io/kubernetes-id: gapps
    syncable.dev/image-digest: unknown
    syncable.dev/generated-by: backstage-scaffolder
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: gapps
      app.kubernetes.io/instance: 9095eef2-gapps
  template:
    metadata:
      labels: *a1
      annotations: *a2
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        fsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: gapps
          image: europe-west2-docker.pkg.dev/syncable-461014/9095eef245584e5513bbe7a21529cd0b88065a6f321e36e304-images/customers/xvtivof7pmczsfw9g1y1ninjnyoooiba-bf282a96/de0916fc-44ee-44f2-a104-5788f3f0ab0a-ff24040f-gapps:2e3842f
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: HOST_NAME
              valueFrom:
                configMapKeyRef:
                  name: gapps-config
                  key: HOST_NAME
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      terminationGracePeriodSeconds: 30
