apiVersion: artifact.gcp.upbound.io/v1beta1
kind: Registry
metadata:
  name: c6c8a61e9962cf9d753246fc27782bd18792ba8878ad6548ae-app-images
  namespace: customer-c6c8a61e9962cf9d753246fc27782bd18792ba8878ad6548ae
  labels:
    app.kubernetes.io/name: app-images
    app.kubernetes.io/managed-by: syncable
    syncable.dev/customer-id: XvtIvof7pmCZSfw9g1y1NInJNYooOIBa
    syncable.dev/project-id: 48fa957e-1e45-4c8f-a37e-fa91f8dede26
    syncable.dev/resource-type: artifact-registry
    syncable.dev/cloud-provider: gcp
  annotations:
    crossplane.io/external-name: c6c8a61e9962cf9d753246fc27782bd18792ba8878ad6548ae-app-images
    syncable.dev/description: Artifact Registry for
      XvtIvof7pmCZSfw9g1y1NInJNYooOIBa/48fa957e-1e45-4c8f-a37e-fa91f8dede26
spec:
  forProvider:
    location: europe-west2
    format: DOCKER
    description: Container registry for Syncable project
      48fa957e-1e45-4c8f-a37e-fa91f8dede26
    cleanupPolicyDryRun: false
  providerConfigRef:
    name: default
