apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-61c5b558-maindb
  namespace: customer-61c5b55857888989272c39be043f64d2a9e7b592c5eb4ba02a
  labels:
    app.kubernetes.io/name: maindb
    app.kubernetes.io/managed-by: syncable
    syncable.dev/customer-id: U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso
    syncable.dev/project-id: 96bdb925-c99f-4adf-8b4c-cb6b61d81673
    syncable.dev/resource-type: postgres-cluster
  annotations:
    syncable.dev/description: CrunchyDB PostgreSQL cluster maindb for customer
      U8TnFI7z1NHnF6ZhQ2TZtTLidSxUkjso
    syncable.dev/created-by: backstage-scaffolder
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  postgresVersion: 17
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: standard
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
              storageClassName: standard
  users:
    - name: dbuser
      databases:
        - db1
      options: NOSUPERUSER
      password:
        type: AlphaNumeric
  proxy:
    pgBouncer:
      replicas: 1
